services:
  web:
    build:
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      DEBUG: 1
    networks:
      - app-network
  vue-app:
    build:
      dockerfile: ./docker/fe/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./fe:/app
      - /app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge